#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

python manage.py shell <<EOF
from django.contrib.auth.models import User

try:
    User.objects.filter(is_superuser=True).delete()
    print("Superusers deleted successfully.")
except Exception as e:
    print("Error occurred while deleting superusers:", e)
EOF

python manage.py createsuperuser --noinput

exec python manage.py runserver_plus 0.0.0.0:8000
