# Generated by Django 4.2.3 on 2023-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fullname", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "contacts",
                "managed": True,
            },
        ),
    ]
