# Generated by Django 4.2.3 on 2023-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="index",
            field=models.BooleanField(default=False, verbose_name="Does it appear in index"),
        ),
    ]
