# Generated by Django 4.2.3 on 2023-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("title_en", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_fr", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_sv", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_de", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("subtitle", models.CharField(max_length=255, verbose_name="subtitle")),
                ("subtitle_en", models.CharField(max_length=255, null=True, verbose_name="subtitle")),
                ("subtitle_fr", models.CharField(max_length=255, null=True, verbose_name="subtitle")),
                ("subtitle_sv", models.CharField(max_length=255, null=True, verbose_name="subtitle")),
                ("subtitle_de", models.CharField(max_length=255, null=True, verbose_name="subtitle")),
                ("description", models.CharField(max_length=255, verbose_name="description")),
                ("description_en", models.CharField(max_length=255, null=True, verbose_name="description")),
                ("description_fr", models.CharField(max_length=255, null=True, verbose_name="description")),
                ("description_sv", models.CharField(max_length=255, null=True, verbose_name="description")),
                ("description_de", models.CharField(max_length=255, null=True, verbose_name="description")),
            ],
            options={
                "verbose_name": "service-index",
            },
        ),
    ]
