# Generated by Django 4.2.3 on 2023-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_serviceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ManyToManyField(to="services.category"),
        ),
    ]
