# Generated by Django 4.2.2 on 2023-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_teammember_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
