# Generated by Django 4.2.3 on 2023-08-15 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0002_alter_feedback_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="subtitle",
            new_name="designation",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="description",
            new_name="quote",
        ),
    ]
